# Generated by Django 4.1.3 on 2022-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_team'),
        ('jwt_auth', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_name',
        ),
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ManyToManyField(blank=True, related_name='club', to='club.club'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='club.team'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
