# Generated by Django 4.1.3 on 2023-01-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
