# Generated by Django 4.1.3 on 2022-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_alter_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
