# Generated by Django 4.1.3 on 2022-11-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_alter_league_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='year',
            new_name='name',
        ),
    ]
