# Generated by Django 4.1.3 on 2022-11-21 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_honours_player_title'),
        ('club', '0004_team_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixture', '0002_fixture_away_team_fixture_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_total_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_total_score',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ManyToManyField(blank=True, related_name='away_fixture', to='club.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ManyToManyField(blank=True, related_name='home_fixture', to='club.team'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_one', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('shot_two', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_result', to='fixture.fixture')),
                ('player', models.ManyToManyField(blank=True, related_name='score', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_results_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
