# Generated by Django 4.1.3 on 2022-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_alter_league_name'),
        ('fixture', '0004_alter_result_fixture_alter_result_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='league',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='season.league'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='season.season'),
        ),
    ]
