# Generated by Django 4.1.3 on 2022-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0008_result_player_id_alter_result_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
