# Generated by Django 4.1.3 on 2022-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('club', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='club_players', to='player.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='team_players', to='player.player'),
        ),
    ]
